#ifndef CONSTANTS_H
#define CONSTANTS_H

// GAME CONFIGURATION

// Game limits
#define MAX_SCORE 9999
#define MAX_ITEMS 39
#define MAX_MINERS 8
#define MAX_SPRITES 40

// Screen configuration
#define SCREEN_TILE_WIDTH 20
#define SCREEN_TILE_HEIGHT 18
#define TILE_SIZE 8

// Map configuration
#define MAP_WIDTH 10
#define MAP_HEIGHT 10
#define MAX_ITEMS_PER_TILE 2

// TILE TYPES

#define TILE_TYPE_NONE 0
#define TILE_TYPE_CONVEYOR 1
#define TILE_TYPE_MINER 2
#define TILE_TYPE_CHEST 3
#define TILE_TYPE_WALL 4
#define TILE_TYPE_COUNT 5

// ITEM TYPES

#define ITEM_TYPE_NONE 0
#define ITEM_TYPE_INGOT 1

// DIRECTIONS

#define DIRECTION_UP 0
#define DIRECTION_RIGHT 1
#define DIRECTION_DOWN 2
#define DIRECTION_LEFT 3

// MENU STATES

#define MENU_NONE 0
#define MENU_ORIENTATION_SELECTION 1
#define MENU_TILE_SELECTION 2

// SPRITE CONFIGURATION

#define UI_SPRITE_CURSOR 0
#define SPRITE_VRAM_INDEX_CURSOR 0
#define SPRITE_VRAM_INDEX_TOTAL 9
#define ITEMS_VRAM_INDEX_TOTAL 1

// TIMING

#define MINER_DEFAULT_RATE 200
#define MINER_DEFAULT_COOLDOWN 0

// GAME INITIALIZATION

#define INITIAL_CURSOR_X 5
#define INITIAL_CURSOR_Y 5
#define INITIAL_CURSOR_DIRECTION DIRECTION_RIGHT

#endif // CONSTANTS_H
